### ISSUE TITLE
Feature Request: Ability to hide/remove "Jobs" from left side menu

### ISSUE THREAD

**Issue by isillo** [crimera/piko#445] opened 2024-10-24 12:14 UTC
Pretty much as title. In Left left where are Profile, Premium, Bookmarks, Lists, Spaces etc there is also Jobs and would be nice to be able to hide it.

**Comment by crimera** [comment] 2024-10-24 22:57
Duplicate of: https://github.com/crimera/piko/issues/398

**Closed by crimera** 2024-10-24 22:57 UTC
